name: Hotfix opened

on:
  pull_request:
    types:
      - labeled

jobs:
  build:
    name: Build
    if: ${{ github.event.label.name == 'hotfix' }}
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # 6.0.3
        with:
          ref: ${{ github.head_ref }}

      - name: Setup Node.js and cache
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # 6.4.0
        with:
          node-version: '24.x'

      - uses: pnpm/action-setup@0e279bb959325dab635dd2c09392533439d90093 # 6.0.8
        name: Install pnpm
        with:
          run_install: false

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # 5.0.5
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('src/pnpm-lock.yaml') }}
          restore-keys: |
              ${{ runner.os }}-pnpm-store-

      - name: Install packages
        run: pnpm i --frozen-lockfile

      - name: Set up Python 3.12.10
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # 6.2.0
        with:
          python-version: 3.12.10

      - name: Install python packages
        working-directory: packages/txc-uploader
        run: pip install -r requirements.dev.txt

      - name: Lint
        run: pnpm run lint

      - name: Test TypeScript compiles
        run: pnpm run tsc:build

      - name: Test
        run: pnpm run test

  create_hotfix_release:
    needs: ['build']
    name: Create hotfix release
    if: ${{ github.event.label.name == 'hotfix' }}
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # 6.0.3
        with:
          ref: ${{ github.head_ref }}

      - name: Get Latest Release
        id: latest_release
        uses: cardinalby/git-get-release-action@2ab178299eecb253f820dcf2cce11f62be1178f7 # 1.2.6
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          latest: true

      - name: Create release
        uses: softprops/action-gh-release@b4309332981a82ec1c5618f44dd2e27cc8bfbfda # 3.0.0
        with:
          tag_name: ${{ github.head_ref }}
          name: Hotfix ${{ steps.latest_release.outputs.tag_name }}
          body: ${{ github.event.pull_request.title }}
          draft: true
