name: Create hotfix

on: workflow_dispatch

jobs:
  build:
    name: Build - ${{ github.ref_name }}
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # 6.0.3
        with:
          ref: ${{ github.ref_name }}

      - name: Setup Node.js and cache
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # 6.4.0
        with:
          node-version: '20.x'

      - uses: pnpm/action-setup@0e279bb959325dab635dd2c09392533439d90093 # 6.0.8
        name: Install pnpm
        with:
          run_install: false

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # 5.0.5
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('src/pnpm-lock.yaml') }}
          restore-keys: |
              ${{ runner.os }}-pnpm-store-

      - name: Install packages
        run: pnpm i --frozen-lockfile

      - name: Lint
        run: pnpm run lint

      - name: Test TypeScript compiles
        run: pnpm run tsc:build

      - name: Test
        run: pnpm run test

  create_hotfix_release:
    needs: ['build']
    name: Create hotfix release
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # 6.0.3
        with:
          ref: ${{ github.ref_name }}

      - name: Get Latest Release
        id: latest_release
        uses: cardinalby/git-get-release-action@2ab178299eecb253f820dcf2cce11f62be1178f7 # 1.2.6
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          latest: true

      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@a22cf08638b34d5badda920f9daf6e72c477b07b # 6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          release_branches: hotfix/*
          custom_tag: ${{ steps.latest_release.outputs.tag_name }}-hotfix
          tag_prefix: ''

      - name: Create release
        uses: softprops/action-gh-release@b4309332981a82ec1c5618f44dd2e27cc8bfbfda # 3.0.0
        with:
          tag_name: ${{ steps.tag_version.outputs.new_tag }}
          name: Hotfix ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}
          draft: true
