name: Manual release
run-name: Manual release of ${{ inputs.tag }} to ${{ inputs.stage }}

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag for the release to trigger the pipeline for, eg v1.1.0'
        type: string
        required: true
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: true
      stage:
        description: 'Stage to deploy to, must match choice of environment'
        type: choice
        options:
          - test
          - preprod
          - prod

jobs:
  deploy:
    name: Deploy to ${{ inputs.stage }}
    environment: ${{ inputs.environment }}
    runs-on: ubuntu-22.04
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout repo
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # 6.0.3
        with:
          ref: ${{ inputs.tag }}

      - name: Setup Node.js and cache
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # 6.4.0
        with:
          node-version: '20.x'

      - uses: pnpm/action-setup@0e279bb959325dab635dd2c09392533439d90093 # 6.0.8
        name: Install pnpm
        with:
          run_install: false

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # 5.0.5
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('src/pnpm-lock.yaml') }}
          restore-keys: |
              ${{ runner.os }}-pnpm-store-

      - name: Install packages
        run: pnpm i --frozen-lockfile

      - name: Assume role using OIDC
        uses: aws-actions/configure-aws-credentials@e7f100cf4c008499ea8adda475de1042d6975c7b # 6.2.0
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/cdd-github-actions-role-eu-west-2
          aws-region: ${{ vars.AWS_DEFAULT_REGION }}

      - name: Deploy to ${{ inputs.stage }}
        env:
          ROOT_DOMAIN: ${{ vars.ROOT_DOMAIN }}
          AWS_SES_IDENTITY_ARN: ${{ secrets.AWS_SES_TEST_IDENTITY }}
          MAP_BOX_ACCESS_TOKEN: ${{ secrets.MAP_BOX_ACCESS_TOKEN }}
          SUPPORT_EMAIL: ${{ secrets.SUPPORT_EMAIL }}
          SUPPORT_PHONE: ${{ secrets.SUPPORT_PHONE }}
          SOURCE_ROLE_ARN: ${{ vars.NAPTAN_ROLE_ARN }}
          NAPTAN_BUCKET_NAME: ${{ vars.NAPTAN_BUCKET_NAME }}
          NAPTAN_BUCKET_REGION: ${{ vars.NAPTAN_BUCKET_REGION }}
          NAPTAN_BUCKET_KEY: ${{ vars.NAPTAN_BUCKET_KEY }}
          NAPTAN_ROLE_ARN: ${{ vars.NAPTAN_ROLE_ARN }}
          NPTG_BUCKET_NAME: ${{ vars.NAPTAN_BUCKET_NAME }}
          NPTG_ROLE_ARN: ${{ vars.NAPTAN_ROLE_ARN }}
          NPTG_BUCKET_KEY: ${{ vars.NPTG_BUCKET_KEY }}
          NOC_BUCKET_NAME: ${{ vars.NOC_BUCKET_NAME }}
          NOC_BUCKET_REGION: ${{ vars.NOC_BUCKET_REGION }}
          NOC_BUCKET_KEY: ${{ vars.NOC_BUCKET_KEY }}
          NOC_ROLE_ARN: ${{ vars.NOC_ROLE_ARN }}
        run: |
          pnpm run deploy --stage ${{ inputs.stage }}
